baseURL = "https://carlguo.com/"
languageCode = "en-us"
title = "Zifan (Carl) Guo | About & portfolio"
pygmentsUseClasses = true
summaryLength = 10

[params]
Description = "Carl Guo is a Computer Science & Math undergrad at MIT interested in AI safety and performance engineering."

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 1

[[menu.main]]
name = "CV"
url = "/portfolio/"
weight = 5

# [[menu.main]]
# name = "Micros"
# url = "/micros/"
# weight = 2

# [[menu.main]]
# name = "Errata"
# url = "/errata/"
# weight = 3

# [[menu.main]]
# name = "Cool"
# url = "/cool/"
# weight = 4

# [[menu.main]]
# name = "Posts"
# url = "/posts/"
# weight = 5

[[menu.main]]
name = "Misc"
url = "/misc/"
weight = 6

# [[menu.main]]
# name = "Resume"
# url = "/resume.pdf"
# weight = 7
