baseURL = "https://tianyuz.me/"
languageCode = "en-us"
title = "Tianyu Zhang"
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 1

# [[menu.main]]
# name = "Micros"
# url = "/micros/"
# weight = 2

# [[menu.main]]
# name = "Errata"
# url = "/errata/"
# weight = 3

[[menu.main]]
name = "Cool"
url = "/cool/"
weight = 4

# [[menu.main]]
# name = "Posts"
# url = "/posts/"
# weight = 5

# [[menu.main]]
# name = "Letter"
# url = "/letter/"
# weight = 6